# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_out', '0002_auto_20161123_0557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
